//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionCactus.BC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cactus()
        {
            this.list_collection = new HashSet<list_collection>();
            this.list_exhibition = new HashSet<list_exhibition>();
        }
    
        public int id_cactus { get; set; }
        public string name { get; set; }
        public string tipe { get; set; }
        public string origin { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> id_instruction { get; set; }
    
        public virtual instruction instruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_collection> list_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_exhibition> list_exhibition { get; set; }
    }
}
