//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionCactus.BC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibition1()
        {
            this.list_exhibition1 = new HashSet<list_exhibition1>();
        }
    
        public int id_exhibition { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string place { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_exhibition1> list_exhibition1 { get; set; }
    }
}
