//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionCactus.BC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cactus1337Entities4 : DbContext
    {
        public cactus1337Entities4()
            : base("name=cactus1337Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cactus> Cactus { get; set; }
        public virtual DbSet<Collection1> Collection1 { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<instruction> instruction { get; set; }
        public virtual DbSet<list_collection> list_collection { get; set; }
        public virtual DbSet<list_exhibition> list_exhibition { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
